name: PR Review Enhancements

on:
  pull_request:
    branches: [main]

jobs:
  optimization-and-link-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for broken links
        uses: lycheeverse/lychee-action@v1.0.8
        with:
          args: --accept 200,403,429 ./**/*.html

      - name: Optimize Images
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

