name: PR Review Enhancements

on:
  pull_request:
    branches: [main]

jobs:
  optimization-and-link-check:
    runs-on: ubuntu-latest

    steps:
      - name: Optimize Images
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

