# name: Update Sitemap and Deploy

# on:
#   push:
#     branches: [main]

# jobs:
#   update-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v3

#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: '3.x'

#       - name: Update Sitemap
#         run: python attsitemap.py

#       - name: Commit and push if changed
#         run: |
#           git config --global user.email "danielmello.nfa@gmail.com"
#           git config --global user.name "DanielMelloo"
#           git add sitemap.xml
#           git commit -m "Update sitemap.xml" || exit 0
#           git remote add origin_with_token https://$PUSHSECRET@github.com/DanielMelloo/CloudHub.git
#           git push origin_with_token main

#       - name: Deploy to GitHub Pages
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token: ${{ secrets.PUSHSECRET }}
#           publish_dir: ./
